---
abstract: 'Connect events to listeners in Dist::Zilla plugins.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Beam-Connector
provides:
  Dist::Zilla::Plugin::Beam::Connector:
    file: lib/Dist/Zilla/Plugin/Beam/Connector.pm
    version: '0.001000'
recommends:
  Moose: '2.000'
requires:
  Moose: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.001000'
